### ISSUE TITLE
Live feature extraction

### ISSUE THREAD

**Issue by saquibntt** [fabienringeval/AVEC2018#1]
Hi,
can the scripts be used for live audio feature extraction? I want to do feature extraction on nvidia jetson TX2 for live emotion recognition.

**Comment by fabienringeval** [comment]
Hi,
This is out of the scope of the challenge. Please refer to the documentation of the used toolboxes (openSMIILE, openFACE) for more details on their real-time possibilities.

**Comment by saquibntt** [comment]
Thank you!
